### PR TITLE
Annotation

### PR DESCRIPTION
**Pull request by jjh42**

### CODE REVIEW

**Comment by koraykv** [comment]
Can you make this base on the current version, I prefer the function to be called :name() rather than graphName() which implies the name for the whole graph rather than this particular node.

**Comment by jjh42** [comment]
@koraykv I used `graphName` and `graphAttributes` because I thought that just having graph call `name` and `attribute` functions might be a bit too general. End users don't generally need to call these functions directly, but they are called by graph when generating the dot file. Maybe `graphNodeName` and `graphNodeAttributes` would be clearer?

I think it is nicer to have the single `annotation` function for end users to use. So naming is just
`:annotate{name = 'MyName'}`. Are you happy with that (i.e. removing the current `name` function)?

**Comment by koraykv** [comment]
I agree with the annotate{} function call and removing the :name() function call and graphNodeName and graphNodeAttributes is fine too.

**Comment by jjh42** [comment]
addressed comments.

**Comment by koraykv** [comment]
Thanks Jonny. Can you produce png files for the images and link them from raw.github.com as it is done for the other images. They are not showing up on the doc page now.

**Pull request merged**
